INSERT INTO stories (name, content, author_id, is_complete) VALUES
('Beyond Words', 'A bell chimes above her as Katy pushes open the old wooden door that leads into Silo’s Books and Curios. She had finally found the small, almost invisible, shop tucked in between a craft store to its right and a health food store to its left. It would have been easy to walk by had you not been expressly looking for it, as Katy had been. Ding, Ding.', 1, false
),
('Mr Grumpy', '“Oh, it must be THAT time of year again!! Gus said, then flicked his tail twice in the direction of his humans moving about large boxes from the loft. These boxes always smelled funny…of mice he wasn’t able to chase, and moisture he didn’t run in. The boxes come down, and the humans start moving around brightly coloured ornaments…or that’s what the call them. Shiny things Gus used to like to play with when her was younger. The balls he was so found of batting around, until one broke and hurt his paw. The yards of tinsel he liked to eat, until it made him sick and his humans had to take him to the vet…that’s about when he really stopped liking Christmas! But there were the lights…those twinkling, magical things that really got his attention. In his old age, they were about the only toy that made him feel like a kitten again. Especially at New Years, when they brought out flashing ones, that made him dance in a hypnotic kitty disco…oh yes, he liked the lights.', 2, false
),
('Cora and Harley', 'Cora peers into the narrow alleyway, spotting the tabby cat in a rough and tumble with a sphynx cat, as they bite into each other, growling. The sphynx cat then successfully pins down the tabby cat and lets out a long hiss before forcing its right paw on the cat’s head . A bright white light along with stardusts soon erupts from the focal point of their contact, blinding the alleyway into oblivion. The white light and stardust begin to dissipate. Cora squints her eyes, trying to make out what’s happening. She sees the tabby cat’s lifeless body on the ground and the sphynx cat is nowhere to be seen.', 2, false
),
('Jack and Jill', 'Jack and Jill went up the hill to fetch a pail of water. Jack fell down and broke his crown and Jill came tumbling after. Up Jack got and home did trot, as fast as he could caper. Went to bed to mend his head with vinegar and brown paper.', 2, true
);
