INSERT INTO contributions (story_id,author_id,content,upvotes) VALUES
(1, 1, 'Katy looks up at the sound, surprised to see not a brass shopkeeper’s bell, but two silver bells that look as though they have just been cut from Santa’s sleigh. The crystal-clear ringing of the bells hangs in the stale air of the otherwise quiet shop long after she shuts the door and cautiously steps within. The lights are dim and the walls are covered from floor to ceiling with tall, rickety shelves. And every inch of every shelf is stuffed, corner to corner, with books! Old books, new books, soft and hard-cover books, picture books, and old boring-looking books. Books, books, books, as far as the eye can see, more books than she has ever seen before.', 2
),
(2, 2, 'There were many other things Gus the grumpy cat didn’t like about this season. The weather for one…he begged his humans to fix it to no avail. It was hard to go out and hunt when it was always raining and cold. Sometimes, there was this white stuff on the ground…Gus hated how that affected his delicate pink paws. He would immediately come back in. A blanket would quickly be thrown over his humans as welcome warmth, and he would knead those paws back to life but jumping laps…mama. papa, mama, papa …finally mama’s voluptuous lap, because she would wrap him in more blankets and rock him in a baby bouncy bounce until he haps into a kitty coma. There he would stay until mama’s bladder was about to burst, and he was deftly slipped to papa’s lap, where he would proudly snuggle on papa’s belly. Well, he did like the extra love and attention he got this time of year, as his family tried to keep warm together.', 0
),
(3, 2, 'At the Tree House group home, Cora is idly playing with a book called “Simple First Words: Let’s Talk,” looking at a picture of a teddy bear and then pressing a button with text that matches the visual. She keeps pressing on the button that makes buzzing noises, after which other kids start screaming and covering their ears. “Cora Young,” a staff member said, “Dear, Dr. Ashley is ready to see you. Come now.” The staff member approaches Cora while extending her hand to grab Cora’s.', 1
),
(1, 2, 'In Katy’s house, where she lives with her mom and dad, all of her parents’ books are kept in a very special glass case, and she is not, under any circumstance, to touch them. Her mom says they are precious and to be treated with respect and that she can read them when she is older. Her dad calls them expensive and not for little girls and their grubby, sticky hands.', 4
)
;
